notifications:
  email: false
language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
cache: pip
script:
  - pipenv run python -m unittest discover -s tests -p '*_test.py'